### ISSUE TITLE
Question: Multiplatform Support

### ISSUE THREAD

**Issue by ronnie-codes** [SwiftfulThinking/SwiftfulRouting#17]
I'm using your package in a SwiftUI + VIPER project of mine to make sure that the Router is implemented properly, which SwiftUI doesn't really make feasible (I'm sure you're aware). 

Anyway, I noticed your stuff doesn't work when targeting macOS, so I'd like to fork this and add multi-platform support. My question is if you would be interested in having that fork merged back in at all.

Good stuff btw.

**Comment by SwiftfulThinking** [comment]
@ronnie-codes I don't work on macOS often, which is why it wasn't included from the start. But yes, I'd definitely be interested in supporting multi-platform and merging back. You're also welcome to open a PR herein if it's easier and/or want me to review.

My only requirement is that the syntax and code-style needs to match the existing codebase!
