### ISSUE TITLE
Add swipe to back

### ISSUE THREAD

**Issue by ferdous-mahmud** [SwiftfulThinking/SwiftfulRouting#57]
Add swipe to back using UINavigationController extension

```swift
extension UINavigationController: UIGestureRecognizerDelegate {
    override open func viewDidLoad() {
        super.viewDidLoad()
        interactivePopGestureRecognizer?.delegate = self
    }
    
    public func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        return viewControllers.count > 1
    }
}

```
# Demo

<img src="https://github.com/SwiftfulThinking/SwiftfulRouting/assets/62091371/0ed594f3-be6f-4c5f-95d5-aba3ec13d9a5" width="50%" height="auto">

**Comment by SwiftfulThinking** [comment]
Thanks for the input. The SwiftUI framework does not have this embedded by default (I'm not sure why tbh), and so I have decided to not include it by default as well. However, I also use this in all of my projects. So instead of including it within the framework, I've updated the Readme so developers can copy & paste. [Added in 5.3.3](https://github.com/SwiftfulThinking/SwiftfulRouting/releases/tag/5.3.3)
